language: node_js
node_js:
  - "18"
  - "20"

os:
  - linux

cache:
  directories:
    - node_modules

before_script:
  - npm ci

script:
  - npm run lint
  - npm run build
  - npm run test

branches:
  only:
    - main
    - master
    - develop
    - /^feature-.*$/

matrix:
  fast_finish: true
  allow_failures:
    - node_js: "20"
